/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kalkulator;


import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
/**
 *
 * @author gokpraz
 */
public class FormClient extends javax.swing.JFrame {

   private String bilangan = "";
   private double bil1 = 0, bil2 = 0, jumlah = 0;
   private int pilih = 0;
   private CalculatorInterface calculator;
   
   public FormClient()
   {
      
      try {
         calculator = (CalculatorInterface) Naming.lookup("rmi://localhost:1099/calculator");
       
      } catch (NotBoundException e) {
         System.out.println("Terjadi error : " + e.getMessage());
         System.exit(1);
      } catch (MalformedURLException e) {
         System.err.println("Terjadi error : " + e.getMessage());
         System.exit(1);
      } catch (RemoteException e) {
         System.out.println("Terjadi error : " + e.getMessage());
         System.exit(1);
      }
      
      initComponents();
      // Membuat inputan readonly
      txtInput.setEditable(false);

      clearData();
      disabledButtonSamaDengan();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtInput = new javax.swing.JTextField();
      btn1 = new javax.swing.JButton();
      btn2 = new javax.swing.JButton();
      btn3 = new javax.swing.JButton();
      btn4 = new javax.swing.JButton();
      btn5 = new javax.swing.JButton();
      btn6 = new javax.swing.JButton();
      btn7 = new javax.swing.JButton();
      btn8 = new javax.swing.JButton();
      btn9 = new javax.swing.JButton();
      btnTambah = new javax.swing.JButton();
      btnKurang = new javax.swing.JButton();
      btnKali = new javax.swing.JButton();
      btnBagi = new javax.swing.JButton();
      btnSamaDengan = new javax.swing.JButton();
      btn0 = new javax.swing.JButton();
      btnClear = new javax.swing.JButton();
      lblNilai1 = new javax.swing.JLabel();
      lblOperasi = new javax.swing.JLabel();
      lblNilai2 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel1.setBackground(new java.awt.Color(255, 255, 255));

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
      jLabel1.setText("Simple Calculator");

      txtInput.setBackground(new java.awt.Color(255, 255, 255));
      txtInput.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
      txtInput.setForeground(new java.awt.Color(0, 0, 0));

      btn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn1.setText("1");
      btn1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn1ActionPerformed(evt);
         }
      });

      btn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn2.setText("2");
      btn2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn2ActionPerformed(evt);
         }
      });

      btn3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn3.setText("3");
      btn3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn3ActionPerformed(evt);
         }
      });

      btn4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn4.setText("4");
      btn4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn4ActionPerformed(evt);
         }
      });

      btn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn5.setText("5");
      btn5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn5ActionPerformed(evt);
         }
      });

      btn6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn6.setText("6");
      btn6.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn6ActionPerformed(evt);
         }
      });

      btn7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn7.setText("7");
      btn7.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn7ActionPerformed(evt);
         }
      });

      btn8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn8.setText("8");
      btn8.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn8ActionPerformed(evt);
         }
      });

      btn9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn9.setText("9");
      btn9.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn9ActionPerformed(evt);
         }
      });

      btnTambah.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btnTambah.setText("+");
      btnTambah.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTambahActionPerformed(evt);
         }
      });

      btnKurang.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btnKurang.setText("-");
      btnKurang.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnKurangActionPerformed(evt);
         }
      });

      btnKali.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btnKali.setText("x");
      btnKali.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnKaliActionPerformed(evt);
         }
      });

      btnBagi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btnBagi.setText(":");
      btnBagi.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBagiActionPerformed(evt);
         }
      });

      btnSamaDengan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btnSamaDengan.setText("=");
      btnSamaDengan.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSamaDenganActionPerformed(evt);
         }
      });

      btn0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btn0.setText("0");
      btn0.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn0ActionPerformed(evt);
         }
      });

      btnClear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      btnClear.setText("C");
      btnClear.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnClearActionPerformed(evt);
         }
      });

      lblNilai1.setText("nilai1");

      lblOperasi.setText("operasi");

      lblNilai2.setText("nilai2");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(16, 16, 16)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                           .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                 .addComponent(btnSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addComponent(btnBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                 .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(82, 82, 82)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNilai1)
                        .addGap(19, 19, 19)
                        .addComponent(lblOperasi)
                        .addGap(18, 18, 18)
                        .addComponent(lblNilai2)
                        .addGap(6, 6, 6)))))
            .addContainerGap(11, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblNilai1)
               .addComponent(lblOperasi)
               .addComponent(lblNilai2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(16, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "3";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn3ActionPerformed

   private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "1";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn1ActionPerformed

   private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "2";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn2ActionPerformed

   private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "4";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn4ActionPerformed

   private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "5";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn5ActionPerformed

   private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "6";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn6ActionPerformed

   private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "7";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn7ActionPerformed

   private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "8";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn8ActionPerformed

   private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "9";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn9ActionPerformed

   private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
      if (bil1 != 0 && bil2 == 0) {
         enabledButtonSamaDengan();
      }
      bilangan += "0";
      txtInput.setText(bilangan);
   }//GEN-LAST:event_btn0ActionPerformed

   private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      txtInput.setText("");
      bil1 = 0.0;
      bil2 = 0.0;
      jumlah = 0.0;
      bilangan = "";
      clearData();
      enabledButtonOperation();
      disabledButtonSamaDengan();
   }//GEN-LAST:event_btnClearActionPerformed

   private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
      lblNilai1.setText(txtInput.getText());
      lblOperasi.setText("+");
      
      bil1 = Double.valueOf(txtInput.getText());
      txtInput.setText("+");
      bilangan = "";
      
      pilih = 1;
      disabledButtonOperation();
   }//GEN-LAST:event_btnTambahActionPerformed

   private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
      lblNilai1.setText(txtInput.getText());
      lblOperasi.setText("-");
      
      bil1 = Double.valueOf(txtInput.getText());
      txtInput.setText("-");
      bilangan = "";
      
      pilih = 2;
      disabledButtonOperation();
   }//GEN-LAST:event_btnKurangActionPerformed

   private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
      lblNilai1.setText(txtInput.getText());
      lblOperasi.setText("x");
      
      bil1 = Double.valueOf(txtInput.getText());
      txtInput.setText("x");
      bilangan = "";
      
      pilih = 3;
      disabledButtonOperation();
   }//GEN-LAST:event_btnKaliActionPerformed

   private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
      lblNilai1.setText(txtInput.getText());
      lblOperasi.setText(":");
      
      bil1 = Double.valueOf(txtInput.getText());
      txtInput.setText(":");
      bilangan = "";
      
      pilih = 4;
      disabledButtonOperation();
   }//GEN-LAST:event_btnBagiActionPerformed

   private void btnSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamaDenganActionPerformed
      // 1 : Tambah ; 2 : Kurang ; 3 : Kali ; 4 : Bagi
      lblNilai2.setText(txtInput.getText());
      
      bil2 = Double.valueOf(txtInput.getText());
      
      try {
         
         switch (pilih) {
            case 1 :
               jumlah = calculator.penjumlahan(bil1, bil2);
            break;
            
            case 2 :
               jumlah = calculator.pengurangan(bil1, bil2);
            break;
            
            case 3 :
               jumlah = calculator.perkalian(bil1, bil2);
            break;
            
            case 4 :
               jumlah = calculator.pembagian(bil1, bil2);
            break;
         }
         
         bilangan = Double.toString(jumlah);
         txtInput.setText(bilangan);
         
         if (bil1 != 0 && bil2 != 0) {
            disabledButtonSamaDengan();
         }
         
      } catch (RemoteException e) {
         System.err.println("Terjadi Error : " + e.getMessage());
         System.exit(1);
      }
   }//GEN-LAST:event_btnSamaDenganActionPerformed

   private void clearData()
   {
      lblNilai1.setText("");
      lblNilai2.setText("");
      lblOperasi.setText("");
   }
   
   private void disabledButtonOperation()
   {
      btnTambah.setEnabled(false);
      btnKurang.setEnabled(false);
      btnBagi.setEnabled(false);
      btnKali.setEnabled(false);
   }
   
   private void enabledButtonOperation()
   {
      btnTambah.setEnabled(true);
      btnKurang.setEnabled(true);
      btnBagi.setEnabled(true);
      btnKali.setEnabled(true);
   }
   
   private void enabledButtonSamaDengan()
   {
      btnSamaDengan.setEnabled(true);
   }

   private void disabledButtonSamaDengan()
   {
      btnSamaDengan.setEnabled(false);
   }   

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn0;
   private javax.swing.JButton btn1;
   private javax.swing.JButton btn2;
   private javax.swing.JButton btn3;
   private javax.swing.JButton btn4;
   private javax.swing.JButton btn5;
   private javax.swing.JButton btn6;
   private javax.swing.JButton btn7;
   private javax.swing.JButton btn8;
   private javax.swing.JButton btn9;
   private javax.swing.JButton btnBagi;
   private javax.swing.JButton btnClear;
   private javax.swing.JButton btnKali;
   private javax.swing.JButton btnKurang;
   private javax.swing.JButton btnSamaDengan;
   private javax.swing.JButton btnTambah;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JLabel lblNilai1;
   private javax.swing.JLabel lblNilai2;
   private javax.swing.JLabel lblOperasi;
   private javax.swing.JTextField txtInput;
   // End of variables declaration//GEN-END:variables
}
